baseURL = "https://jinzhao.info/"
languageCode = "zh-cn"
title = "Lambda"
theme = "m10c"
canonifyurls = true
publishDir = "docs"
pygmentsCodeFences = true
paginate = 20

# Add your own params here
[params]
  author = "jin.zhao"
  avatar = "/img/avatar.jpg"
  description = "Calculations and Programming"

  # Choose your social networks
  github = "JinWuZhao"
  [[params.social]]
    name = "github"
    url = "https://github.com/jinwuzhao"
